
 drop table if exists logged_in_users CASCADE ;
 drop table if exists login_history CASCADE ;
 drop table if exists roles CASCADE ;
 drop table if exists user_roles CASCADE ;
 drop table if exists users CASCADE ;
 create table logged_in_users (id integer generated by default as identity, time timestamp, user_id bigint, primary key (id))  ;
 create table login_history (id integer generated by default as identity, time timestamp, user_id bigint, primary key (id)) ;
 create table roles (id integer generated by default as identity, name varchar(20), primary key (id)) ;
 create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) ;
 create table users (id bigint generated by default as identity, email varchar(255),  password varchar(255), name varchar(255), username varchar(255), primary key (id)) ;
 alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username) ;
 alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email) ;
 alter table logged_in_users add constraint FKqub26qkp52dxcdxmsjrfqy7aw foreign key (user_id) references users ;
 alter table login_history add constraint FK20v0mimmdegh2afs39uixlxpm foreign key (user_id) references users ;
 alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles ;
 alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users ;
 INSERT INTO `users` VALUES (1, 'zaki@gmail.com', '$2a$10$yrD32OnJlQhZgFpOtzOb5.NR62aNtbM9/ZCg5uSXMmr0G.AUm5/EK', 'zaki', 'zaki');
INSERT INTO `users` VALUES (2, 'me.alhussain@gmail.com', '$2a$10$eG3LWAWRZlcWHAf81KT5vegzMk0Xh7Mm6oTKWIbgK1pOZDnBWLoWy', 'alhussainie', 'alhussainie');
INSERT INTO `roles` VALUES (1, 'ROLE_ADMIN');
INSERT INTO `roles` VALUES (2, 'ROLE_USER');
INSERT INTO `user_roles` VALUES (2, 1);
INSERT INTO `user_roles` VALUES (1, 1);
INSERT INTO `login_history` VALUES (1, '2021-07-04 02:53:13', 2);
 